os:
  - windows
  - linux
#  - osx - disabled, need to figure out cmake OPENSSL

language: c

env:
  - BRANCH=1.2.6
  - BRANCH=devel

cache:
  directories:
    - "$HOME/.choosenim"

install:
  - curl https://gist.github.com/genotrance/fb53504a4fba88bc5201d3783df5c522/raw/travis.sh -LsSf -o travis.sh
  - source travis.sh

script:
  - nimble install -d -y
  - nimble test
